### ISSUE TITLE
No Icon on Thunderbird 102.9

### ISSUE THREAD

**Issue by kstev99** [SaltyAimbOtter/Thunderbird-ProtonMail-Addon#1]
Am I missing something?   There is no icon in the toolbar, and none available from the customize menu.   Using Dark/Black theme (v102.0)

**Comment by SaltyAimbOtter** [comment]
Hey, I'm still on 102.8.0 but according to the change-log for 102.9 nothing in this regard has been changed.
This is where the icon is placed, perhaps you are searching in the wrong place?
![image](https://user-images.githubusercontent.com/40303883/227523951-e2d7119e-3d30-4b25-958c-30cf44854129.png)

**Comment by kstev99** [comment]
Thank You.  I hadn't looked in the "Spaces Toolbar" and normally keep it collapsed.  
Thanks for pointing it out, and for taking the time for this extension.  Closing ticket
